### ISSUE TITLE
运行过程似乎有问题

### ISSUE THREAD

**Issue by jnxyp** [ohyooo/Five_in_a_Row#1]
每次都要在控制台输入两次坐标.....第一次输入的坐标貌似被丢掉了
另外建议加一个棋盘网格，以及人人对战
电脑只是随机的话不太好玩

**Comment by ohyooo** [comment]
惊了个呆(´･_･`)竟然有人看(*・０・)
这只是一次作业，想着赶快弄好就交了，没考虑这么多
电脑下棋的话可以考虑改成在上一次落子的周围
网络的话当时还没学，都没往这上面想
其实做成界面的样式体验会好点，就是懒改了。。。
